apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
data:
  {{- with .Values.secret }}
  .dockerconfigjson: {{ .dockerConfigJson }}
  {{- end }}
type: {{ .Values.secret.type }}