variable "eks_cluster_name" {}
variable "subnet_ids" {}
variable "desired_size" {}
variable "max_size" {}
variable "min_size" {}
variable "max_unavailable" {}
variable "instance_types" {}
variable "eks_cluster_autoscaler_name" {}
variable "iam_user_arn" {}