name: CI/CD - Build & Push to Docker Hub

on:
  push:
    branches:
      - dev
      - main
jobs:
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -f app.api/app.dockerfile  -t hungtran126/fast-api:${{ github.sha }} .
        
      - name: Push Docker image to Docker hub
        run: |
          docker push hungtran126/fast-api:${{ github.sha }}