name: Terraform Destroy Infra

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "confirm" to destroy the infrastructure'
        required: true
        default: ""
  push:
    branches:
      - main
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    if: inputs.confirmation == 'confirm'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configuration the AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ap-southeast-1
          role-session-name: ${{ secrets.ROLE_SESSION_NAME }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.3

      - name: Terraform Init
        working-directory: app.tf
        run: terraform init --backend-config="key=github_ci/infra/${{ github.ref_name }}-tf.tfstate"
        # run: cd app.tf && terraform init

      - name: Terraform Plan
        working-directory: app.tf
        run: terraform plan -destroy -var-file=envs/${{ github.ref_name }}.tfvars

      - name: Terraform Destroy
        working-directory: app.tf
        run: terraform destroy -var-file=envs/${{ github.ref_name }}.tfvars --auto-approve
