name: Terraform Destroy

on:
  workflow_dispatch: 
    inputs:
      confirmation:
        description: 'Type "confirm" to destroy the infrastructure'
        required: true
        default: 'confirm'

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configuration the AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::025066273464:role/github-svc-tf-provision-iac
          aws-region: ap-southeast-1
          role-session-name: github-actions-destroy-iac

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.3

      - name: Terraform Init
        run: terraform init --backend-config="key=github_ci/infra/${{ github.ref_name }}-tf.tfstate"

      - name: Terraform Plan
        run: terraform plan -destroy -var-file=envtfvars/${{ github.ref_name }}.tfvars

      - name: Terraform Destroy
        if: inputs.confirmation == 'confirm'
        run: terraform destroy -var-file=envtfvars/${{ github.ref_name }}.tfvars --auto-approve

